name: DevCard

on:
    workflow_dispatch:
    push:
        branches:
            - main
    schedule:
        - cron: "0 4 * * 1"

jobs:
    devcard:
        runs-on: ubuntu-latest
        steps:
            - name: devcard
              uses: dailydotdev/action-devcard@2.0.4
              with:
                  devcard_id: ${{ secrets.DEVCARD_ID }}
